### ISSUE TITLE
-m dma option mentioned in README is not supported by fuzz_probe.py

### ISSUE THREAD

**Issue by C0D1NGK1NG** [yiluwusbu/DEVFUZZ#1]
In the "Fuzzing with Device Models" section of the README, under "Post-Probing Phase Fuzzing," the following example command is provided:
`sudo python3 ./tools/fuzz_probe.py -c 0 -s 0 -d e1000 -p 50 -m dma`
However, the dma option is not supported in fuzz_probe.py. The relevant function in the script is:
`def mode_to_int(mode):
  if mode == "baseline":
    return 1
  elif mode == 'fuzz':
    return 2
  elif mode == "no_fuzz":
    return 3
  else:
    raise Exception("Unknown mode")
`
The script only supports the following modes: baseline, fuzz, and no_fuzz. The dma option mentioned in the README example is not implemented.

**Comment by yiluwusbu** [comment]
Sorry about the wrong script name in the READEME instruction. Post-probing  fuzzing should use fuzz.py. As the name suggusts, fuzz_probe.py is used only for probing phase fuzzing, where DMA is not initialized yet (or being intialized).   I will update the README.
